### ISSUE TITLE
Failed to extract files with Command line installation

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb-suite#2]
Hello guys!

I am reporting the following issue. It happens both on my local machine (Windows 10 64 bit, openjdk 11.0.24 2024-07-16), and on a Ubuntu 22.04 server 64 bit (Java 11 installed via standard repository via apt), accessed via ssh.

Problem: the command line installation results in unpacking **only** the plugin folders (if requested) and the uninstaller folder. All remaining files/folders are _not_ extracted to the desired folder.

We use exactly the same command as described in the [docs](https://3dcitydb-docs.readthedocs.io/en/latest/first-steps/install-impexp.html#command-line-installation): 

`java -jar 3DCityDB-Importer-Exporter-5.5.0-Setup.jar -console`

FYI:
a) the third installation method works fine, as intended, i.e. creating and using a custom XML-based setup script. 
b) the GUI based installation works fine, as intended
c) We encounter the same issue also with some older versions (we tried a couple of 5.x versions)

Are we overlooking something?

Best regards,

GA

**Comment by clausnagel** [comment]
Hi @gioagu, this is a known issue: https://github.com/3dcitydb/importer-exporter/issues/286

Unfortunately, the issue is in the third-party tool IzPack that we use for building the installer. So, we cannot fix it. If you need to install the Importer/Exporter on a headless machine, a workaround is to first install it on a GUI machine and afterwards zip the installation folder and copy it on your headless machine. Alternatively, you can directly use the release packages of the Importer/Exporter and of each plugin you need. They are just ZIP packages and can easily be unzipped on your headless machine.

**Comment by gioagu** [comment]
OK, all clear! Thanks for the link, I did not check in the specific importer-exporter issues... ;-)
Still, good that we have the issue mentioned also here for those users that simply download the suite.
As written, we have actually already solved the problem, using the xml configuration file. All fine!

Thanks for the quick reply!

GA
